apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-prod
resources:
  - ../../base
  - ../../../redis/base
  - namespace.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
images:
  - name: ghcr.io/taixingbi/layer-rag-query-v1
    newName: ghcr.io/taixingbi/layer-rag-query-v1
    newTag: "7a53e5d07508"
    digest: "sha256:e6e08864bc77a990f87aff1aadd80ab2b90d01381e7083744fd0cb441e3fa593"
