apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-prod
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
images:
  - name: ghcr.io/taixingbi/layer-rag-query-v1
    newName: ghcr.io/taixingbi/layer-rag-query-v1
    newTag: "8e670ff1f4b6"
    digest: "sha256:7db25db8758c85ad30d0f51afe1099a5369293466c83338fc9c0604712481f44"
