apiVersion: apps/v1
kind: Deployment
metadata:
  name: layer-rag-query
  labels:
    environment: prod
spec:
  template:
    metadata:
      labels:
        environment: prod
    spec:
      containers:
        - name: rag-query
          env:
            - name: ENV
              value: "prod"
            - name: QDRANT_URL
              value: "http://qdrant.ai-dev.svc.cluster.local:6333"
            - name: EMBEDDING_URL
              value: "http://layer-gateway-embedding.ai-dev.svc.cluster.local:8000"
            - name: INFERENCE_URL
              value: "http://layer-gateway-inference.ai-dev.svc.cluster.local:8000"
            - name: RERANK_URL
              value: "http://layer-gateway-reranker.ai-dev.svc.cluster.local:8000"
