apiVersion: v1
kind: Service
metadata:
  name: layer-gateway-reranker
  labels:
    environment: dev
spec:
  type: NodePort
  selector:
    app: layer-gateway-reranker
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30182
