apiVersion: v1
kind: Service
metadata:
  name: layer-mcp-github
  labels:
    environment: dev
spec:
  type: NodePort
  selector:
    app: layer-mcp-github
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30191
