apiVersion: v1
kind: Service
metadata:
  name: layer-web
  labels:
    environment: dev
spec:
  type: NodePort
  selector:
    app: layer-web
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30186
