apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-github-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/taixingbi/huntai-k3s.git
    targetRevision: main
    path: manifests/tool/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
