apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orchestrator-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/taixingbi/huntai-k3s.git
    targetRevision: main
    path: manifests/orchestrator/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
