apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-query-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: ai-prod
  source:
    repoURL: https://github.com/taixingbi/huntai-k3s.git
    targetRevision: main
    path: manifests/rag/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
