apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-prod
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
images:
  - name: ghcr.io/taixingbi/layer-orchestrator-v1
    newName: ghcr.io/taixingbi/layer-orchestrator-v1
    newTag: "18656145e393"
    digest: "sha256:a1c7de80d83c0591a9235c15b69c4a277e4bc6973ae2798269e6a0ecd15738e2"
