apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-prod
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
images:
  - name: ghcr.io/taixingbi/layer-orchestrator-v1
    newName: ghcr.io/taixingbi/layer-orchestrator-v1
    newTag: "234a6dcc074a"
    digest: "sha256:cae9650384146bff3d61700a6fe370a42157cc90514f32ff0969ad9fad1b9447"
