apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  labels:
    app: qdrant
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
