apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-prod
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
  - path: patch-guest-chat.yaml
images:
  - name: ghcr.io/taixingbi/layer-web-v1
    newName: ghcr.io/taixingbi/layer-web-v1
    newTag: "3b1d3092c2e9"
    digest: "sha256:a36a952829c1a8c2b7763308359c0c6e361622bf30ec0bb91761ab75e31fc734"
