apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-prod
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
  - path: patch-guest-chat.yaml
images:
  - name: ghcr.io/taixingbi/layer-web-v1
    newName: ghcr.io/taixingbi/layer-web-v1
    newTag: "ad3b4d3eaef4"
    digest: "sha256:1ce2f233210a5d4b2132e6fb65d11b620ca07a8add7a72af6e396224afbc06cb"
