apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-prod
resources:
  - ../../base
  - namespace.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
  - path: patch-guest-chat.yaml
images:
  - name: ghcr.io/taixingbi/layer-web-v1
    newName: ghcr.io/taixingbi/layer-web-v1
    newTag: "784753e58bd5"
    digest: "sha256:820e0247705cd58e7a2b39b09fda1402cede1bbb2372968671750f8ae5d77c70"
